// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'ai-panel-error'
  | 'ai-panel-ready'
  | 'ai-panel-sidenav-tooltip'
  | 'ai-panel-studying'
  | 'ai-panel-title'
  | 'pref-api-base-url'
  | 'pref-api-key'
  | 'pref-auto-study'
  | 'pref-model'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
